package it.mig.sies.type.foglicomplementari;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2025-07-25T10:27:28.213+02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "trasferisciFoglioComplementare", 
                  wsdlLocation = "file:/C:/LAVORO/Progetti/WSAxisTest/AxisTestClientWeb/WebContent/wsdl/IntegrazioneSiesAdn/trasferisciFoglioComplementare.wsdl",
                  targetNamespace = "http://it/mig/sies/type/fogliComplementari") 
public class TrasferisciFoglioComplementare_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://it/mig/sies/type/fogliComplementari", "trasferisciFoglioComplementare");
    public final static QName TrasferisciFoglioComplementare = new QName("http://it/mig/sies/type/fogliComplementari", "trasferisciFoglioComplementare");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/LAVORO/Progetti/WSAxisTest/AxisTestClientWeb/WebContent/wsdl/IntegrazioneSiesAdn/trasferisciFoglioComplementare.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TrasferisciFoglioComplementare_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/LAVORO/Progetti/WSAxisTest/AxisTestClientWeb/WebContent/wsdl/IntegrazioneSiesAdn/trasferisciFoglioComplementare.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TrasferisciFoglioComplementare_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TrasferisciFoglioComplementare_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrasferisciFoglioComplementare_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrasferisciFoglioComplementare_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrasferisciFoglioComplementare_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TrasferisciFoglioComplementare_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TrasferisciFoglioComplementare
     */
    @WebEndpoint(name = "trasferisciFoglioComplementare")
    public TrasferisciFoglioComplementare getTrasferisciFoglioComplementare() {
        return super.getPort(TrasferisciFoglioComplementare, TrasferisciFoglioComplementare.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrasferisciFoglioComplementare
     */
    @WebEndpoint(name = "trasferisciFoglioComplementare")
    public TrasferisciFoglioComplementare getTrasferisciFoglioComplementare(WebServiceFeature... features) {
        return super.getPort(TrasferisciFoglioComplementare, TrasferisciFoglioComplementare.class, features);
    }

}
