package it.mig.sies.type.foglicomplementari;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "trasferisciFoglioComplementare", targetNamespace = "http://it/mig/sies/type/fogliComplementari")
public interface TrasferisciFoglioComplementare {

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "http://it/mig/sies/type/fogliComplementari")
	@RequestWrapper(localName = "trasferisciFoglioComplementare", targetNamespace = "http://it/mig/sies/type/fogliComplementari", className = "it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementare_Type")
	@ResponseWrapper(localName = "trasferisciFoglioComplementareResponse", targetNamespace = "http://it/mig/sies/type/fogliComplementari", className = "it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementareResponse")
	public String trasferisciFoglioComplementare(
			@WebParam(name = "xml", targetNamespace = "http://it/mig/sies/type/fogliComplementari")
			String xml);

}
