package it.mig.sies.type.foglicomplementari;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2025-07-25T10:27:28.170+02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://it/mig/sies/type/fogliComplementari", name = "trasferisciFoglioComplementare")
@XmlSeeAlso({ObjectFactory.class})
public interface TrasferisciFoglioComplementare {

    @WebMethod
    @RequestWrapper(localName = "trasferisciFoglioComplementare", targetNamespace = "http://it/mig/sies/type/fogliComplementari", className = "it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementare_Type")
    @ResponseWrapper(localName = "trasferisciFoglioComplementareResponse", targetNamespace = "http://it/mig/sies/type/fogliComplementari", className = "it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementareResponse")
    @WebResult(name = "return", targetNamespace = "http://it/mig/sies/type/fogliComplementari")
    public java.lang.String trasferisciFoglioComplementare(
        @WebParam(name = "xml", targetNamespace = "http://it/mig/sies/type/fogliComplementari")
        java.lang.String xml
    );
}
