
package it.giustizia.serviziTelematici.reginde.interrogazioniInt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-12-16T15:59:37.954+01:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "SearchLimitException", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt")
public class SearchLimitException_Exception extends Exception {
    
    private it.giustizia.serviziTelematici.reginde.interrogazioniInt.SearchLimitException searchLimitException;

    public SearchLimitException_Exception() {
        super();
    }
    
    public SearchLimitException_Exception(String message) {
        super(message);
    }
    
    public SearchLimitException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SearchLimitException_Exception(String message, it.giustizia.serviziTelematici.reginde.interrogazioniInt.SearchLimitException searchLimitException) {
        super(message);
        this.searchLimitException = searchLimitException;
    }

    public SearchLimitException_Exception(String message, it.giustizia.serviziTelematici.reginde.interrogazioniInt.SearchLimitException searchLimitException, Throwable cause) {
        super(message, cause);
        this.searchLimitException = searchLimitException;
    }

    public it.giustizia.serviziTelematici.reginde.interrogazioniInt.SearchLimitException getFaultInfo() {
        return this.searchLimitException;
    }
}
