package it.giustizia.serviziTelematici.reginde.interrogazioniInt;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1 2020-12-16T15:59:38.006+01:00 Generated source
 * version: 2.7.14.redhat-1
 *
 */
@WebServiceClient(name = "WsServiziInterrogazioneInterni", wsdlLocation = "ServiziInterrogazioneInterni.wsdl", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt")
public class WsServiziInterrogazioneInterni_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName(
			"http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt",
			"WsServiziInterrogazioneInterni");
	public final static QName ServiziInterrogazioneInterniBeanPort = new QName(
			"http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt",
			"ServiziInterrogazioneInterniBeanPort");
	static {
		URL url = null;
		try {
			// url = new URL("file:/siesWeb/defaultroot/wsdl/ServiziInterrogazioneInterni.wsdl");
			url = new URL(WsServiziInterrogazioneInterni_Service.class
					.getResource("ServiziInterrogazioneInterni.wsdl"), "ServiziInterrogazioneInterni.wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(WsServiziInterrogazioneInterni_Service.class.getName()).log(
					java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
					"ServiziInterrogazioneInterni.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public WsServiziInterrogazioneInterni_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public WsServiziInterrogazioneInterni_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WsServiziInterrogazioneInterni_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public WsServiziInterrogazioneInterni_Service(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public WsServiziInterrogazioneInterni_Service(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
	// compliant code instead.
	public WsServiziInterrogazioneInterni_Service(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns WsServiziInterrogazioneInterni
	 */
	@WebEndpoint(name = "ServiziInterrogazioneInterniBeanPort")
	public WsServiziInterrogazioneInterni getServiziInterrogazioneInterniBeanPort() {
		return super.getPort(ServiziInterrogazioneInterniBeanPort, WsServiziInterrogazioneInterni.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
	 *            features not in the <code>features</code> parameter will have their default values.
	 * @return returns WsServiziInterrogazioneInterni
	 */
	@WebEndpoint(name = "ServiziInterrogazioneInterniBeanPort")
	public WsServiziInterrogazioneInterni getServiziInterrogazioneInterniBeanPort(
			WebServiceFeature... features) {
		return super.getPort(ServiziInterrogazioneInterniBeanPort, WsServiziInterrogazioneInterni.class,
				features);
	}

}
