package it.giustizia.serviziTelematici.reginde.interrogazioniInt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2020-12-16T15:59:37.985+01:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt", name = "WsServiziInterrogazioneInterni")
@XmlSeeAlso({it.giustizia.serviziTelematici.reginde.interrogazioniExt.ObjectFactory.class, ObjectFactory.class})
public interface WsServiziInterrogazioneInterni {

    @WebMethod
    @RequestWrapper(localName = "ricercaEnteComplete", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt", className = "it.giustizia.serviziTelematici.reginde.interrogazioniInt.RicercaEnteComplete")
    @ResponseWrapper(localName = "ricercaEnteCompleteResponse", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt", className = "it.giustizia.serviziTelematici.reginde.interrogazioniInt.RicercaEnteCompleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<it.giustizia.serviziTelematici.reginde.interrogazioniExt.Ruoloente> ricercaEnteComplete(
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(name = "descrizione", targetNamespace = "")
        java.lang.String descrizione,
        @WebParam(name = "codiceEnte", targetNamespace = "")
        java.lang.String codiceEnte,
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        java.lang.String codiceFiscale,
        @WebParam(name = "indirizzoPec", targetNamespace = "")
        java.lang.String indirizzoPec
    ) throws SearchLimitException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaSoggettoComplete", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt", className = "it.giustizia.serviziTelematici.reginde.interrogazioniInt.RicercaSoggettoComplete")
    @ResponseWrapper(localName = "ricercaSoggettoCompleteResponse", targetNamespace = "http://www.giustizia.it/serviziTelematici/reginde/interrogazioniInt", className = "it.giustizia.serviziTelematici.reginde.interrogazioniInt.RicercaSoggettoCompleteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<it.giustizia.serviziTelematici.reginde.interrogazioniExt.Soggetto> ricercaSoggettoComplete(
        @WebParam(name = "cognome", targetNamespace = "")
        java.lang.String cognome,
        @WebParam(name = "nome", targetNamespace = "")
        java.lang.String nome,
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        java.lang.String codiceFiscale,
        @WebParam(name = "indirizzo", targetNamespace = "")
        java.lang.String indirizzo,
        @WebParam(name = "codiceEnte", targetNamespace = "")
        java.lang.String codiceEnte,
        @WebParam(name = "orderBy", targetNamespace = "")
        java.lang.String orderBy,
        @WebParam(name = "asc", targetNamespace = "")
        java.lang.Boolean asc
    ) throws SearchLimitException_Exception;
}
