package it.mig.sies.type.esecuzione_NEW;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * iscriviProvvedimentoEsecuzione_NEW service = new iscriviProvvedimentoEsecuzione_NEW();
 * IscriviProvvedimentoEsecuzioneNEW portType = service.getIscriviProvvedimentoEsecuzioneNEW();
 * portType.iscriviProvvedimentoEsecuzioneNEW(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "iscriviProvvedimentoEsecuzione_NEW", targetNamespace = "http://it/mig/sies/type/esecuzione_NEW", wsdlLocation = "file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/esecuzione_NEW.wsdl")
public class IscriviProvvedimentoEsecuzioneNEW_Service extends Service {

	private final static URL ISCRIVIPROVVEDIMENTOESECUZIONENEW_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(it.mig.sies.type.esecuzione_NEW.IscriviProvvedimentoEsecuzioneNEW_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = it.mig.sies.type.esecuzione_NEW.IscriviProvvedimentoEsecuzioneNEW_Service.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/esecuzione_NEW.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/esecuzione_NEW.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ISCRIVIPROVVEDIMENTOESECUZIONENEW_WSDL_LOCATION = url;
	}

	public IscriviProvvedimentoEsecuzioneNEW_Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IscriviProvvedimentoEsecuzioneNEW_Service() {
		super(ISCRIVIPROVVEDIMENTOESECUZIONENEW_WSDL_LOCATION, new QName(
				"http://it/mig/sies/type/esecuzione_NEW",
				"iscriviProvvedimentoEsecuzione_NEW"));
	}

	/**
	 * 
	 * @return returns IscriviProvvedimentoEsecuzioneNEW
	 */
	@WebEndpoint(name = "iscriviProvvedimentoEsecuzione_NEW")
	public IscriviProvvedimentoEsecuzioneNEW getIscriviProvvedimentoEsecuzioneNEW() {
		return super.getPort(new QName(
				"http://it/mig/sies/type/esecuzione_NEW",
				"iscriviProvvedimentoEsecuzione_NEW"),
				IscriviProvvedimentoEsecuzioneNEW.class);
	}

}
