package it.mig.sies.type.esecuzione_NEW;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "iscriviProvvedimentoEsecuzione_NEW", targetNamespace = "http://it/mig/sies/type/esecuzione_NEW")
public interface IscriviProvvedimentoEsecuzioneNEW {

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "iscriviProvvedimentoEsecuzione_NEW")
	@WebResult(targetNamespace = "http://it/mig/sies/type/esecuzione_NEW")
	@RequestWrapper(localName = "iscriviProvvedimentoEsecuzione_NEW", targetNamespace = "http://it/mig/sies/type/esecuzione_NEW", className = "it.mig.sies.type.esecuzione_NEW.IscriviProvvedimentoEsecuzioneNEW_Type")
	@ResponseWrapper(localName = "iscriviProvvedimentoEsecuzione_NEWResponse", targetNamespace = "http://it/mig/sies/type/esecuzione_NEW", className = "it.mig.sies.type.esecuzione_NEW.IscriviProvvedimentoEsecuzioneNEWResponse")
	public String iscriviProvvedimentoEsecuzioneNEW(
			@WebParam(name = "xml", targetNamespace = "http://it/mig/sies/type/esecuzione_NEW")
			String xml);

}
