<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="iscriviProvvedimentoEsecuzione_NEWDefinitions"
				targetNamespace="http://it/mig/sies/type/esecuzione_NEW" xmlns=""
				xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
				xmlns:s1="http://it/mig/sies/type/esecuzione_NEW"
				xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/"
				xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <s0:types>
  	<xsd:schema>
		<xsd:import namespace="http://it/mig/sies/type/esecuzione_NEW"
			schemaLocation="ProvvedimentoEsecuzione_NEW.xsd" />
	</xsd:schema>
    <xs:schema attributeFormDefault="unqualified"
    			elementFormDefault="qualified"
    			targetNamespace="http://it/mig/sies/type/esecuzione_NEW"
    			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
    			xmlns:s1="http://it/mig/sies/type/esecuzione_NEW"
    			xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/"
    			xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="iscriviProvvedimentoEsecuzione_NEW">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="xml" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="iscriviProvvedimentoEsecuzione_NEWResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </s0:types>
  <s0:message name="iscriviProvvedimentoEsecuzione_NEW">
    <s0:part element="s1:iscriviProvvedimentoEsecuzione_NEW" name="parameters"/>
  </s0:message>
  <s0:message name="iscriviProvvedimentoEsecuzione_NEWResponse">
    <s0:part element="s1:iscriviProvvedimentoEsecuzione_NEWResponse" name="parameters"/>
  </s0:message>
  <s0:portType name="iscriviProvvedimentoEsecuzione_NEW">
    <s0:operation name="iscriviProvvedimentoEsecuzione_NEW" parameterOrder="parameters">
      <s0:input message="s1:iscriviProvvedimentoEsecuzione_NEW"/>
      <s0:output message="s1:iscriviProvvedimentoEsecuzione_NEWResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="iscriviProvvedimentoEsecuzione_NEWSoapBinding" type="s1:iscriviProvvedimentoEsecuzione_NEW">
    <s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="iscriviProvvedimentoEsecuzione_NEW">
      <s2:operation style="document"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="iscriviProvvedimentoEsecuzione_NEW">
    <s0:port binding="s1:iscriviProvvedimentoEsecuzione_NEWSoapBinding" name="iscriviProvvedimentoEsecuzione_NEW">
      <s2:address location="http://localhost:7001/siesEsecuzione_NEW/iscriviProvvedimentoEsecuzione_NEW"/>
    </s0:port>
  </s0:service>
</s0:definitions>