log4j.rootLogger=OFF

log4j.logger.it.mig.sies=ALL,destLogEsecuzione
# MEV 16 CUMULO: aggiunta scrittura queries nel file di log
log4j.logger.java.sql=ALL, destLogEsecuzione

# Serve per evitare che le loggature di SIES finiscano anche sul rootLogger
log4j.additivity.it.mig.sies=false

# APPENDER 
log4j.appender.destLogEsecuzione.layout=org.apache.log4j.PatternLayout
log4j.appender.destLogEsecuzione=org.apache.log4j.RollingFileAppender
log4j.appender.destLogEsecuzione.Threshold=DEBUG
log4j.appender.destLogEsecuzione.File=${jboss.server.log.dir}/sies/siesEsecuzione.log
log4j.appender.destLogEsecuzione.Append=true
log4j.appender.destLogEsecuzione.MaxFileSize=1000KB
log4j.appender.destLogEsecuzione.MaxBackupIndex=10
log4j.appender.destLogEsecuzione.layout.ConversionPattern=%d{DATE} %-5p %-15c{1}: %m%n