# LE PROPRIETA' PER L'INVOCAZIONE DEI WS SONO STATE SPOSTATE SUL FILE DI CONFIG

# LOCALE 		http://localhost:7001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# COLLAUDO_BIL	https://mev.casellario.giustizia.it/siesEsecuzione/iscriviProvvedimentoEsecuzione
# COLLAUDO1		http://10.5.194.166:8001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# COLLAUDO2		http://10.5.194.176:8001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# PREESERCIZIO 	http://10.5.193.155:14001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# ESERCIZIO 	https://casellario.giustizia.it/siesEsecuzione/iscriviProvvedimentoEsecuzione
# PRECOLLAUDO	http://10.5.207.119:8001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# 139			http://10.5.207.139:7001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# PREMERGE
# PRECOLLAUDO	http://10.5.207.119:10001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# PRECOLL HTTPS	https://10.5.207.119:11080/siesEsecuzione/iscriviProvvedimentoEsecuzione
# MERGE MEV31BIS
# PRECOLLAUDO	http://10.5.207.119:8001/siesEsecuzione/iscriviProvvedimentoEsecuzione
# PRECOLL HTTPS	https://10.5.207.119:9000/siesEsecuzione/iscriviProvvedimentoEsecuzione
#nsc.address=https://10.5.207.119:11080/siesEsecuzione/iscriviProvvedimentoEsecuzione

# MEV 16: aggiunto indirizzo
#tfc.address=http://10.5.207.119:11080/sies/trasferisciFoglioComplementare

# MEV 16: aggiunte abilitazioni per profilo 4, 30, 40, 50
profili.abilitati.inserimento=51|52|14|24|4|30|40|50
profili.abilitati.modifica=51|52|14|24|4|30|40|50
profili.abilitati.cancellazione=51|52|14|24|4|30|40|50
profili.abilitati.storico=51|52|14|24|4|30|40|50

# MEV 16: aggiunti codici SP + AEP
codici.sospensionepena=0061|0063|0078|0117|0364|0365|0495
codici.avvenutaesecuzionepena=0006|0081|0083|0096|0097|0098|0099|0424|0473|0587|0588|2245|2630|UTE1

# MEV 23010 - MERGE v10: aggiunti tre codici
blocco.terzo.collegato.nullo=C00400200009|C00400200010|C00400920009|C00400920010|C00400930009|C00400930010|C00400940009|C00400940010|C00400950009|C00400950010|C00401000009|C00401000010|C00401010009|C00401010010|C00401020009|C00401020010|C00401030009|C00401030010|C00401980009|C00401980010|C00403170009|C00403170010|U03727020009|U03722990009|U03722810009

messaggio.201=INSERIMENTO EFFETTUATO CON SUCCESSO. 
messaggio.202=MODIFICA EFFETTUATA CON SUCCESSO. 
messaggio.203=CANCELLAZIONE EFFETTUATA CON SUCCESSO. 
messaggio.204=ATTENZIONE SONO STATI RISCONTRATI DEGLI ERRORI SUL PROVVEDIMENTO TRASMESSO. VERIFICA L'ESTRATTO E PROVVEDI ALLA CORREZIONE.
messaggio.205=ATTENZIONE SONO STATI RISCONTRATI DEGLI ERRORI IN SEDE DI FORMAZIONE DELL'ESTRATTO. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.206=ATTENZIONE SONO STATI RISCONTRATI DEGLI ERRORI IN SEDE DI VALIDAZIONE.
messaggio.207=ATTENZIONE SONO STATI RISCONTRATI DEGLI ERRORI IN SEDE DI VERIFICA DELL'ESTRATTO.
messaggio.400=ERRORE: DATI TRASMESSI NON CORRETTI. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.401=ERRORE: IL SOGGETTO NON RISULTA PRESENTE SUL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANAGRAFICI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.402=ERRORE: PER IL SOGGETTO RISULTANO PRESENTI DEGLI OMONIMI SUL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANAGRAFICI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.403=ERRORE: PER IL SOGGETTO SUL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANAGRAFICI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.404=ERRORE: IL TITOLO ESECUTIVO NON RISULTA PRESENTE TRA LE ISCRIZIONI DEL SOGGETTO, PROVA A VERIFICARE I DATI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.405=ERRORE: IL PROVVEDIMENTO TRASMESSO RISULTA GIA' PRESENTE SUL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
# MEV 16: modificato msg di errore SIUS --> SIES (3 occorrenze)
messaggio.406=ERRORE: IL SOGGETTO DI SIES NON RISULTA COERENTE CON QUELLO DEL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANAGRAFICI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.407=ERRORE: IL TUO UFFICIO NON E' ABILITATO ALLA MODIFICA DEI DATI. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.408=ERRORE: IL PROVVEDIMENTO TRASMESSO E' COLLEGATO AD ALTRI TITOLI, PROVA A VERIFICARE I DATI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.409=ERRORE: PER IL TITOLO ESECUTIVO RISULTANO DELLE DIFFORMITA' TRA IL SIES E IL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.410=ERRORE: IL PROVVEDIMENTO NON RISULTA PRESENTE TRA LE ISCRIZIONI DEL SOGGETTO, PROVA A VERIFICARE I DATI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
messaggio.411=ERRORE: IL PROVVEDIMENTO TRASMESSO NON E' ASSOCIABILE.
messaggio.412=ERRORE: IL PROVVEDIMENTO TRASMESSO NON E' ISCRIVIBILE IN QUANTO NON RISULTA ASSOCIATO SUL SIES IL TITOLO ESECUTIVO SIEP.
# MEV 16 + MEV 31: aggiunto msg di errore per sinonimia
messaggio.413=ERRORE: PER IL SOGGETTO RISULTANO PRESENTI DEI SINONIMI SUL SISTEMA INFORMATIVO DEL CASELLARIO, PROVA A VERIFICARE I DATI ANAGRAFICI ANCHE MEDIANTE L'UTILIZZO DEL MODULO WEB.
# MEV 16 CUMULO: aggiunto msg di errore per elenco provvedimenti NSC
#messaggio.414=ATTENZIONE: PER POTER CONFERMARE IL TRASFERIMENTO DEL PROVVEDIMENTO DI CUMULO ALMENO IL 70% DEI PROVVEDIMENTI CUMULATI DEVE APPARTENERE AL SOGGETTO PRINCIPALE.
messaggio.414=Situazione sul SIC del cumulo emesso dalla Procura della repubblica di {0} in data {1} nei confronti di {2} nat{3} il {4} in {5}
messaggio.500=ERRORE NON PREVISTO. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.501=ERRORE: SONO STATI RISCONTRATI DELLE DIFFORMITA' SUI CODICI UNIVOCI. ERRORE TECNICO :  CONTATTARE L'HELP DESK.
messaggio.502=ERRORE NELL'INSERIMENTO DEI DATI NEL DATA BASE DEL SIC. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.503=ERRORE NELLA MODIFICA DEI DATI DEL DATA BASE DEL SIC. ERRORE TECNICO : CONTATTARE L'HELP DESK.
messaggio.504=ERRORE NELLA CANCELLAZIONE DEI DATI DEL DATA BASE DEL SIC. ERRORE TECNICO : CONTATTARE  L'HELP DESK.
messaggio.505=ERRORE NON PREVISTO. ERRORE TECNICO : CONTATTARE L'HELP DESK.

messaggio.errore.caricamento=ERRORE INTERNO NEL CARICAMENTO DELLE INFORMAZIONI DAL DATABASE LOCALE. ERRORE TECNICO : CONTATTARE L'HELPDESK.
messaggio.errore.comunicazione=ERRORE INTERNO NELLA COMUNICAZIONE CON IL SERVIZIO SIC. ERRORE TECNICO : CONTATTARE L'HELPDESK.
messaggio.errore.elaborazione=ERRORE NELLA FASE DI ELABORAZIONE DEI DATI DI RISPOSTA. ERRORE TECNICO : CONTATTARE L'HELPDESK.
messaggio.errore.profilo=ERRORE: L'UTENTE NON E' ABILITATO AL TRASFERIMENTO.
messaggio.errore.storico=ERRORE INTERNO NEL CARICAMENTO DELLO STORICO. ERRORE TECNICO : CONTATTARE L'HELPDESK.

# MEV 23010
messaggio.errore.controllo.blocco.terzo.collegato=ERRORE: IMPOSSIBILE TRASFERIRE IL PROVVEDIMENTO IN QUANTO MANCA IL RIFERIMENTO AD ALTRO TITOLO.

messaggio.INSERT=INSERIMENTO EFFETTUATO CON SUCCESSO. 
messaggio.UPDATE=MODIFICA EFFETTUATA CON SUCCESSO. 
messaggio.DELETE=CANCELLAZIONE EFFETTUATA CON SUCCESSO. 

# MEV 06
messaggio.delete.superflua=CANCELLAZIONE NON NECESSARIA SUL SIC: FOGLIO COMPLEMENTARE NON TRASMESSO.

# MEV 16
messaggio.errore.controllo.procedimento.non.validato=ERRORE: VALIDARE IL PROCEDIMENTO PRIMA DI PROCEDERE CON LA TRASMISSIONE DEL FOGLIO COMPLEMENTARE.

# MEV 16 CUMULO: aggiunti msgs descrittivi dello stato dei titoli esecutivi legati al CUMULO
messaggio.1=IL PROVVEDIMENTO NON E' PRESENTE SULL'ANAGRAFICA PRINCIPALE.
messaggio.2=IL SOGGETTO ASSOCIATO AL PROVVEDIMENTO NON ESISTE SU NSC.
messaggio.3=IL SOGGETTO ASSOCIATO AL PROVVEDIMENTO E' UN A/R DEL PRINCIPALE ED IL PROVVEDIMENTO E' ASSOCIATO AL PRINCIPALE.
messaggio.4=IL PROVVEDIMENTO E' ASSOCIATO ALL'ANAGRAFICA INDICATA NEL TAG PROVVEDIMENTO - REPLICA.
messaggio.5=IL PROVVEDIMENTO NON E' ASSOCIATO ALL'ANAGRAFICA INDICATA NEL TAG PROVVEDIMENTO.
messaggio.6=IL PROVVEDIMENTO E' PRESENTE SULL'ANAGRAFICA PRINCIPALE.
messaggio.V=VALIDATO
messaggio.L=IN LAVORAZIONE
messaggio.S=VERIFICATO SENZA ERRORI
messaggio.E=VERIFICATO CON ERRORI
messaggio.P=PROVVISORIO
messaggio.D=PROVVISORIO ATTRIBUITO A DIVERSO SOGGETTO
messaggio.N=PROVVEDIMENTO NON ESISTENTE
messaggio.Z=SOGGETTO NON ESISTENTE
messaggio.H=PROVVEDIMENTO NON ASSOCIATO ANAGRAFICA PRINCIPALE