<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap"
	xmlns:intf="http://it/eng/giustizia/avvocatura/ws/dettaglioProcedimento/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://it/eng/giustizia/avvocatura/ws/dettaglioProcedimento/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://it/eng/giustizia/avvocatura/ws/dettaglioProcedimento/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://it/eng/giustizia/avvocatura/ws/dettaglioProcedimento/">
			<element name="DettaglioProcedimento">
				<complexType>
					<sequence>
						<element name="datiProcedimentoInput" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
			<element name="DettaglioProcedimentoResponse">
				<complexType>
					<sequence>
						<element name="datiProcedimentoOutput" type="xsd:string" />
					</sequence>
				</complexType>
			</element>
		</schema>
	</wsdl:types>
	<wsdl:message name="DettaglioProcedimentoRequest">
		<wsdl:part element="tns:DettaglioProcedimento" name="datiProcedimentoInput" />
	</wsdl:message>
	<wsdl:message name="DettaglioProcedimentoResponse">
		<wsdl:part element="tns:DettaglioProcedimentoResponse" name="datiProcedimentoOutput" />
	</wsdl:message>
	<wsdl:portType name="dettaglioProcedimento">
		<wsdl:operation name="DettaglioProcedimento">
			<wsdl:input message="tns:DettaglioProcedimentoRequest" />
			<wsdl:output message="tns:DettaglioProcedimentoResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="dettaglioProcedimento" type="tns:dettaglioProcedimento">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="DettaglioProcedimento">
			<soap:operation
				soapAction="http://it/eng/giustizia/avvocatura/ws/dettaglioProcedimento/DettaglioProcedimento" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="dettaglioProcedimento">
		<wsdl:port binding="tns:dettaglioProcedimento" name="dettaglioProcedimento">
			<soap:address location="http://localhost:8080/services/dettaglioProcedimento" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
