<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://it/eng/giustizia/avvocatura/ws/ricercaSoggettiConProcedimenti/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="ricercaSoggettiConProcedimenti"
	targetNamespace="http://it/eng/giustizia/avvocatura/ws/ricercaSoggettiConProcedimenti/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import
				namespace="http://it/eng/giustizia/avvocatura/ws/type/ricercaSoggettiConProcedimenti"
				schemaLocation="ricerca_soggetto.xsd" />
		</xsd:schema>
		<xsd:schema
			targetNamespace="http://it/eng/giustizia/avvocatura/ws/ricercaSoggettiConProcedimenti/">
			<xsd:element name="RicercaSoggettiConProcedimenti">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="datiSoggettoInput" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="RicercaSoggettiConProcedimentiResponse">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="datiSoggettoOutput" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="RicercaSoggettiConProcedimentiResponse">
		<wsdl:part element="tns:RicercaSoggettiConProcedimentiResponse"
			name="datiSoggettoOutput">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="RicercaSoggettiConProcedimentiRequest">
		<wsdl:part element="tns:RicercaSoggettiConProcedimenti"
			name="datiSoggettoInput">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="ricercaSoggettiConProcedimenti">
		<wsdl:operation name="RicercaSoggettiConProcedimenti">
			<wsdl:input message="tns:RicercaSoggettiConProcedimentiRequest">
			</wsdl:input>
			<wsdl:output message="tns:RicercaSoggettiConProcedimentiResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ricercaSoggettiConProcedimenti" type="tns:ricercaSoggettiConProcedimenti">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="RicercaSoggettiConProcedimenti">
			<soap:operation
				soapAction="http://it/eng/giustizia/avvocatura/ws/ricercaSoggettiConProcedimenti/RicercaSoggettiConProcedimenti" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ricercaSoggettiConProcedimenti">
		<wsdl:port binding="tns:ricercaSoggettiConProcedimenti"
			name="ricercaSoggettiConProcedimenti">
			<soap:address
				location="http://localhost:8080/services/ricercaSoggettiConProcedimenti" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
