<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.giustizia.it/serviziTelematici/pstbe/gestione" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.giustizia.it/serviziTelematici/serviziGenerici" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServiziInvioPagamentiTelematiciBeanService" targetNamespace="http://www.giustizia.it/serviziTelematici/serviziGenerici">
	<types>
		<xs:schema xmlns:ns1="http://www.giustizia.it/serviziTelematici/serviziGenerici" xmlns:tns="http://www.giustizia.it/serviziTelematici/pstbe/gestione" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.giustizia.it/serviziTelematici/pstbe/gestione" version="1.0">
			<xs:import namespace="http://www.giustizia.it/serviziTelematici/serviziGenerici"/>
			<xs:complexType name="datiRiscossione">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codCausale" type="xs:string"/>
							<xs:element minOccurs="0" name="descCausale" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceUtilizzatore" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceGeneratore" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceVersamento" type="xs:string"/>
							<xs:element minOccurs="0" name="tassonomia" type="xs:string"/>
							<xs:element minOccurs="0" name="distrettoUfficio" type="xs:boolean"/>
							<xs:element minOccurs="0" name="visibile" type="xs:boolean"/>
							<xs:element name="beneficiarioSettore" type="xs:boolean"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType abstract="true" name="anagrafica">
				<xs:sequence/>
			</xs:complexType>
			<xs:complexType name="cdo">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codice" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="numeroAlbo" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="parteCausa">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element name="abilitato" type="xs:boolean"/>
							<xs:element minOccurs="0" name="codiceFiscale" type="xs:string"/>
							<xs:element minOccurs="0" name="cognome" type="xs:string"/>
							<xs:element minOccurs="0" name="dataCreazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="nome" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="definizioneServizio">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codice" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="note" type="xs:string"/>
							<xs:element minOccurs="0" name="visibile" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="definizioneTemplate">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="pspCode" type="xs:string"/>
							<xs:element minOccurs="0" name="templateContent" type="xs:string"/>
							<xs:element minOccurs="0" name="templateName" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="pda">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoHash" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoSSL" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="codFornitore" type="xs:string"/>
							<xs:element minOccurs="0" name="codPagTel" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceAlbo" type="xs:string"/>
							<xs:element minOccurs="0" name="dataAutorizzazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="dataCessazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="descEstesa" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="flagPdaPagTel" type="xs:string"/>
							<xs:element minOccurs="0" name="fornitori" type="tns:fornitori"/>
							<xs:element minOccurs="0" name="legaleRappresentante" type="xs:string"/>
							<xs:element minOccurs="0" name="linkManOp" type="xs:string"/>
							<xs:element minOccurs="0" name="nomeCertificatoSSL" type="xs:string"/>
							<xs:element minOccurs="0" name="note" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="sedeLegale" type="xs:string"/>
							<xs:element minOccurs="0" name="tipologia" type="tns:tipologiaPda"/>
							<xs:element minOccurs="0" name="url" type="xs:string"/>
							<xs:element minOccurs="0" name="urlWebService" type="xs:string"/>
							<xs:element name="visibile" type="xs:boolean"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="fornitori">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="tipologiaPda">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="uffici">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoCifra" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="certificatoMimetype" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceGL" type="xs:string"/>
							<xs:element name="codiceRegione" type="xs:int"/>
							<xs:element minOccurs="0" name="codiceUfficioMaster" type="xs:string"/>
							<xs:element minOccurs="0" name="comune" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="indirizzoPec" type="xs:string"/>
							<xs:element minOccurs="0" name="nomeCertificatoCifra" type="xs:string"/>
							<xs:element minOccurs="0" name="provincia" type="xs:string"/>
							<xs:element minOccurs="0" name="tipoUfficio" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="servizi">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="dataAttivazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="note" type="xs:string"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="registri" type="ns1:registro"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="serviziAtti" nillable="true" type="tns:serviziAtti"/>
							<xs:element minOccurs="0" name="tipoServizio" type="tns:definizioneServizio"/>
							<xs:element minOccurs="0" name="url" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="serviziAtti">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="dataDecreto" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="decreto" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="fase" type="xs:string"/>
							<xs:element minOccurs="0" name="grado" type="xs:string"/>
							<xs:element minOccurs="0" name="mimetype" type="xs:string"/>
							<xs:element minOccurs="0" name="nomeDecreto" type="xs:string"/>
							<xs:element minOccurs="0" name="note" type="xs:string"/>
							<xs:element minOccurs="0" name="rito" type="xs:string"/>
							<xs:element minOccurs="0" name="servizio" type="xs:string"/>
							<xs:element minOccurs="0" name="qName" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="ufficiGiudiziari">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoCifra" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="certificatoMimetype" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceUfficioMaster" type="xs:string"/>
							<xs:element minOccurs="0" name="comune" type="xs:string"/>
							<xs:element minOccurs="0" name="descMaster" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="gestoreLocale" type="tns:gestoreLocale"/>
							<xs:element minOccurs="0" name="indirizzoPec" type="xs:string"/>
							<xs:element minOccurs="0" name="nomeCertificatoCifra" type="xs:string"/>
							<xs:element minOccurs="0" name="provincia" type="xs:string"/>
							<xs:element minOccurs="0" name="regione" type="tns:regioni"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="servizi" nillable="true" type="tns:servizi"/>
							<xs:element minOccurs="0" name="tipoUfficio" type="tns:tipiUfficio"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="gestoreLocale">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoSSL" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="distretto" type="tns:distretti"/>
							<xs:element minOccurs="0" name="url" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="distretti">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceGestoreLocale" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="regioni">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="tipiUfficio">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="gruppo" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="ufficiPenale">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="attiDepositabiliUfficio" nillable="true" type="tns:attiDepositabiliUfficio"/>
							<xs:element minOccurs="0" name="certificatoCifra" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="citta" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="gestoreLocale" type="tns:gestoreLocale"/>
							<xs:element minOccurs="0" name="indirizzoPec" type="xs:string"/>
							<xs:element minOccurs="0" name="nomeCertificatoCifra" type="xs:string"/>
							<xs:element minOccurs="0" name="provincia" type="xs:string"/>
							<xs:element minOccurs="0" name="regione" type="tns:regioni"/>
							<xs:element minOccurs="0" name="tipiAttoDepositabile" type="tns:tipiAttoDepositabile"/>
							<xs:element minOccurs="0" name="tipoUfficio" type="tns:tipiUfficio"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="attiDepositabiliUfficio">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceUfficio" type="xs:string"/>
							<xs:element minOccurs="0" name="dtAttivazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="nomeFile" type="xs:string"/>
							<xs:element minOccurs="0" name="normativa" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="note" type="xs:string"/>
							<xs:element minOccurs="0" name="tipoAttoDep" type="tns:tipiAttoDepositabile"/>
							<xs:element minOccurs="0" name="ufficioInterno" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="tipiAttoDepositabile">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="enti">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codice" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceFiscale" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element maxOccurs="unbounded" minOccurs="0" name="indirizzi" nillable="true" type="tns:indirizziAbilitati"/>
							<xs:element minOccurs="0" name="partitaIva" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="indirizziAbilitati">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceFiscaleFirma" type="xs:string"/>
							<xs:element minOccurs="0" name="pec" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="download">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="dataAvviso" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="dataDownload" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="destinazione" type="xs:string"/>
							<xs:element minOccurs="0" name="sito" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="rito">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="registro" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="lookupUfficio">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceFiscale" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="gestoreLocale" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="contenutoRichiestaRtag">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element name="annullamento" type="xs:int"/>
							<xs:element minOccurs="0" name="dataRegistrazione" type="xs:dateTime"/>
							<xs:element minOccurs="0" name="dataRegistrazioneConstraint" type="ns1:dateConstraint"/>
							<xs:element minOccurs="0" name="destinazione" type="xs:string"/>
							<xs:element minOccurs="0" name="erroreServer" type="xs:string"/>
							<xs:element minOccurs="0" name="hostInvio" type="xs:string"/>
							<xs:element minOccurs="0" name="hostRicezione" type="xs:string"/>
							<xs:element minOccurs="0" name="idMessaggio" type="xs:string"/>
							<xs:element name="progressivo" type="xs:int"/>
							<xs:element minOccurs="0" name="richiesta" type="tns:richiestaRtag"/>
							<xs:element minOccurs="0" name="sorgente" type="xs:string"/>
							<xs:element minOccurs="0" name="tipologia" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="richiestaRtag">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="idRepertorio" type="xs:string"/>
							<xs:element minOccurs="0" name="idUnivoco" type="xs:string"/>
							<xs:element minOccurs="0" name="ufficio" type="tns:lookupUfficio"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="lookupRepertorio">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="altriSoggetti">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="codice" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="pecAddr" type="xs:string"/>
							<xs:element minOccurs="0" name="tipologia" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="causalePagamentoConf">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="canalePagamento" type="xs:string"/>
							<xs:element minOccurs="0" name="cfBeneficiario" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceCausale" type="xs:string"/>
							<xs:element minOccurs="0" name="descBeneficiario" type="xs:string"/>
							<xs:element minOccurs="0" name="descCCP" type="xs:string"/>
							<xs:element minOccurs="0" name="ibanAccredito" type="xs:string"/>
							<xs:element minOccurs="0" name="ibanAppoggio" type="xs:string"/>
							<xs:element minOccurs="0" name="metodoPagamento" type="xs:string"/>
							<xs:element minOccurs="0" name="numeroCCP" type="xs:string"/>
							<xs:element minOccurs="0" name="tipoBeneficiario" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="causalePagamentoNEPConf">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="canalePagamento" type="xs:string"/>
							<xs:element minOccurs="0" name="cfBeneficiario" type="xs:string"/>
							<xs:element minOccurs="0" name="codiceCausale" type="xs:string"/>
							<xs:element minOccurs="0" name="descBeneficiario" type="xs:string"/>
							<xs:element minOccurs="0" name="descCCP" type="xs:string"/>
							<xs:element minOccurs="0" name="ibanAccredito" type="xs:string"/>
							<xs:element minOccurs="0" name="ibanAppoggio" type="xs:string"/>
							<xs:element minOccurs="0" name="importo" type="xs:float"/>
							<xs:element minOccurs="0" name="metodoPagamento" type="xs:string"/>
							<xs:element minOccurs="0" name="numeroCCP" type="xs:string"/>
							<xs:element minOccurs="0" name="tipoBeneficiario" type="xs:string"/>
							<xs:element minOccurs="0" name="tipologia" type="xs:string"/>
							<xs:element minOccurs="0" name="ufficioNEP" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="applicazioni">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoHash" type="xs:string"/>
							<xs:element minOccurs="0" name="certificatoSSL" type="xs:base64Binary"/>
							<xs:element minOccurs="0" name="codPagTel" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="url" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
			<xs:complexType name="ufficioInterno">
				<xs:complexContent>
					<xs:extension base="tns:anagrafica">
						<xs:sequence>
							<xs:element minOccurs="0" name="id" type="xs:string"/>
							<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
							<xs:element minOccurs="0" name="tipoUfficio" type="xs:string"/>
						</xs:sequence>
					</xs:extension>
				</xs:complexContent>
			</xs:complexType>
		</xs:schema>
		<xs:schema xmlns:ns1="http://www.giustizia.it/serviziTelematici/pstbe/gestione" xmlns:tns="http://www.giustizia.it/serviziTelematici/serviziGenerici" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.giustizia.it/serviziTelematici/serviziGenerici" version="1.0">
			<xs:import namespace="http://www.giustizia.it/serviziTelematici/pstbe/gestione"/>
			<xs:element name="ServiziPagamentiException" type="tns:ServiziPagamentiException"/>
			<xs:element name="downloadAvviso" type="tns:downloadAvviso"/>
			<xs:element name="downloadAvvisoResponse" type="tns:downloadAvvisoResponse"/>
			<xs:element name="eliminaRichiesta" type="tns:eliminaRichiesta"/>
			<xs:element name="eliminaRichiestaResponse" type="tns:eliminaRichiestaResponse"/>
			<xs:element name="generaAvviso" type="tns:generaAvviso"/>
			<xs:element name="generaAvvisoResponse" type="tns:generaAvvisoResponse"/>
			<xs:element name="generaRPT" type="tns:generaRPT"/>
			<xs:element name="generaRPTResponse" type="tns:generaRPTResponse"/>
			<xs:element name="inviaCarrelloRPT" type="tns:inviaCarrelloRPT"/>
			<xs:element name="inviaCarrelloRPTResponse" type="tns:inviaCarrelloRPTResponse"/>
			<xs:element name="inviaER" type="tns:inviaER"/>
			<xs:element name="inviaERResponse" type="tns:inviaERResponse"/>
			<xs:element name="listaConfNEP" type="tns:listaConfNEP"/>
			<xs:element name="listaConfNEPResponse" type="tns:listaConfNEPResponse"/>
			<xs:element name="listaDatiRiscossione" type="tns:listaDatiRiscossione"/>
			<xs:element name="listaDatiRiscossioneResponse" type="tns:listaDatiRiscossioneResponse"/>
			<xs:element name="registraRispostaWisp" type="tns:registraRispostaWisp"/>
			<xs:element name="registraRispostaWispResponse" type="tns:registraRispostaWispResponse"/>
			<xs:element name="richiediCopiaRT" type="tns:richiediCopiaRT"/>
			<xs:element name="richiediCopiaRTResponse" type="tns:richiediCopiaRTResponse"/>
			<xs:element name="verificaRichiesta" type="tns:verificaRichiesta"/>
			<xs:element name="verificaRichiestaResponse" type="tns:verificaRichiestaResponse"/>
			<xs:complexType name="listaDatiRiscossione">
				<xs:sequence>
					<xs:element minOccurs="0" name="idtipologia" type="xs:string"/>
					<xs:element minOccurs="0" name="codice" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="listaDatiRiscossioneResponse">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="datiRiscossione" type="ns1:datiRiscossione"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="registro">
				<xs:sequence>
					<xs:element minOccurs="0" name="codice" type="xs:string"/>
					<xs:element minOccurs="0" name="codiceApplicazione" type="xs:string"/>
					<xs:element minOccurs="0" name="descrizione" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="dateConstraint">
				<xs:sequence>
					<xs:element minOccurs="0" name="lower" type="xs:dateTime"/>
					<xs:element minOccurs="0" name="upper" type="xs:dateTime"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="verificaRichiesta">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceCRS" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="verificaRichiestaResponse">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ServiziPagamentiException">
				<xs:sequence>
					<xs:element minOccurs="0" name="CRS" type="xs:string"/>
					<xs:element minOccurs="0" name="message" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="eliminaRichiesta">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceCRS" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="eliminaRichiestaResponse">
				<xs:sequence/>
			</xs:complexType>
			<xs:complexType name="generaRPT">
				<xs:sequence>
					<xs:element minOccurs="0" name="richiestaPagamentoTelematico" type="tns:richiestaPagamentoTelematico"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="richiestaPagamentoTelematico">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceDistretto" type="xs:string"/>
					<xs:element minOccurs="0" name="codiceUfficio" type="xs:string"/>
					<xs:element name="autenticazioneSoggetto" type="xs:string"/>
					<xs:element name="soggettoPagatore" type="tns:anagraficaSoggetto"/>
					<xs:element name="datiVersamento" type="tns:datiVersamento"/>
					<xs:element minOccurs="0" name="dataScadenza" type="xs:dateTime"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="anagraficaSoggetto">
				<xs:sequence>
					<xs:element minOccurs="0" name="naturaGiuridica" type="xs:string"/>
					<xs:element name="codiceIdentificativoUnivoco" type="xs:string"/>
					<xs:element name="nominativo" type="xs:string"/>
					<xs:element minOccurs="0" name="indirizzo" type="xs:string"/>
					<xs:element minOccurs="0" name="civico" type="xs:string"/>
					<xs:element minOccurs="0" name="cap" type="xs:string"/>
					<xs:element minOccurs="0" name="localita" type="xs:string"/>
					<xs:element minOccurs="0" name="provincia" type="xs:string"/>
					<xs:element minOccurs="0" name="regione" type="xs:string"/>
					<xs:element minOccurs="0" name="nazione" type="xs:string"/>
					<xs:element minOccurs="0" name="email" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="datiVersamento">
				<xs:sequence>
					<xs:element name="importoTotale" type="xs:decimal"/>
					<xs:element maxOccurs="unbounded" name="datiSingoloVersamento" type="tns:datiSingoloVersamento"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="datiSingoloVersamento">
				<xs:sequence>
					<xs:element name="importo" type="xs:decimal"/>
					<xs:element minOccurs="0" name="causale" type="xs:string"/>
					<xs:element name="datiSpecificiRiscossione" type="xs:string"/>
					<xs:element minOccurs="0" name="datiMarcaBolloDigitale" type="tns:datiMarcaBolloDigitale"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="datiMarcaBolloDigitale">
				<xs:sequence>
					<xs:element name="tipoBollo" type="xs:string"/>
					<xs:element name="hashDocumento" type="xs:string"/>
					<xs:element name="provinciaResidenza" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="generaRPTResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="xmlRPT" type="xs:base64Binary"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="inviaCarrelloRPT">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceFiscale" type="xs:string"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="crs" type="xs:string"/>
					<xs:element name="areaPubblica" type="xs:boolean"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="inviaCarrelloRPTResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="urlWISP" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="registraRispostaWisp">
				<xs:sequence>
					<xs:element minOccurs="0" name="idSession" type="xs:string"/>
					<xs:element minOccurs="0" name="esito" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="registraRispostaWispResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="esitoRispostaWisp" type="tns:esitoRispostaWisp"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="esitoRispostaWisp">
				<xs:sequence>
					<xs:element minOccurs="0" name="areaPubblica" type="xs:boolean"/>
					<xs:element name="pagamentoBollo" type="xs:boolean"/>
					<xs:element minOccurs="0" name="urlRedirect" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="listaConfNEP">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceUfficioNEP" type="xs:string"/>
					<xs:element minOccurs="0" name="tipologia" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="listaConfNEPResponse">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="causalePagamentoNEPConf" type="ns1:causalePagamentoNEPConf"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="richiediCopiaRT">
				<xs:sequence>
					<xs:element minOccurs="0" name="codiceCRS" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="richiediCopiaRTResponse">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="inviaER">
				<xs:sequence>
					<xs:element minOccurs="0" name="idRevoca" type="xs:string"/>
					<xs:element minOccurs="0" name="dataRevoca" type="xs:dateTime"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="inviaERResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="generaAvviso">
				<xs:sequence>
					<xs:element minOccurs="0" name="richiestaPagamentoTelematico" type="tns:richiestaPagamentoTelematico"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="generaAvvisoResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="tns:esitoGeneraAvviso"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="esitoGeneraAvviso">
				<xs:sequence>
					<xs:element minOccurs="0" name="bollettino" type="xs:base64Binary"/>
					<xs:element minOccurs="0" name="numeroAvviso" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="downloadAvviso">
				<xs:sequence>
					<xs:element minOccurs="0" name="numeroAvviso" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="downloadAvvisoResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="xs:base64Binary"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</types>
	<message name="ServiziInvioPagamentiTelematici_downloadAvviso">
		<part element="tns:downloadAvviso" name="downloadAvviso"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_eliminaRichiesta">
		<part element="tns:eliminaRichiesta" name="eliminaRichiesta"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_registraRispostaWispResponse">
		<part element="tns:registraRispostaWispResponse" name="registraRispostaWispResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_downloadAvvisoResponse">
		<part element="tns:downloadAvvisoResponse" name="downloadAvvisoResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_generaAvviso">
		<part element="tns:generaAvviso" name="generaAvviso"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_verificaRichiesta">
		<part element="tns:verificaRichiesta" name="verificaRichiesta"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_richiediCopiaRT">
		<part element="tns:richiediCopiaRT" name="richiediCopiaRT"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_listaConfNEP">
		<part element="tns:listaConfNEP" name="listaConfNEP"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_generaRPT">
		<part element="tns:generaRPT" name="generaRPT"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_inviaCarrelloRPT">
		<part element="tns:inviaCarrelloRPT" name="inviaCarrelloRPT"/>
	</message>
	<message name="ServiziPagamentiException">
		<part element="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_richiediCopiaRTResponse">
		<part element="tns:richiediCopiaRTResponse" name="richiediCopiaRTResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_registraRispostaWisp">
		<part element="tns:registraRispostaWisp" name="registraRispostaWisp"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_listaDatiRiscossione">
		<part element="tns:listaDatiRiscossione" name="listaDatiRiscossione"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_generaAvvisoResponse">
		<part element="tns:generaAvvisoResponse" name="generaAvvisoResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_inviaER">
		<part element="tns:inviaER" name="inviaER"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_listaConfNEPResponse">
		<part element="tns:listaConfNEPResponse" name="listaConfNEPResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_eliminaRichiestaResponse">
		<part element="tns:eliminaRichiestaResponse" name="eliminaRichiestaResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_listaDatiRiscossioneResponse">
		<part element="tns:listaDatiRiscossioneResponse" name="listaDatiRiscossioneResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_inviaCarrelloRPTResponse">
		<part element="tns:inviaCarrelloRPTResponse" name="inviaCarrelloRPTResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_inviaERResponse">
		<part element="tns:inviaERResponse" name="inviaERResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_verificaRichiestaResponse">
		<part element="tns:verificaRichiestaResponse" name="verificaRichiestaResponse"/>
	</message>
	<message name="ServiziInvioPagamentiTelematici_generaRPTResponse">
		<part element="tns:generaRPTResponse" name="generaRPTResponse"/>
	</message>
	<portType name="ServiziInvioPagamentiTelematici">
		<operation name="downloadAvviso" parameterOrder="downloadAvviso">
			<input message="tns:ServiziInvioPagamentiTelematici_downloadAvviso"/>
			<output message="tns:ServiziInvioPagamentiTelematici_downloadAvvisoResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="eliminaRichiesta" parameterOrder="eliminaRichiesta">
			<input message="tns:ServiziInvioPagamentiTelematici_eliminaRichiesta"/>
			<output message="tns:ServiziInvioPagamentiTelematici_eliminaRichiestaResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="generaAvviso" parameterOrder="generaAvviso">
			<input message="tns:ServiziInvioPagamentiTelematici_generaAvviso"/>
			<output message="tns:ServiziInvioPagamentiTelematici_generaAvvisoResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="generaRPT" parameterOrder="generaRPT">
			<input message="tns:ServiziInvioPagamentiTelematici_generaRPT"/>
			<output message="tns:ServiziInvioPagamentiTelematici_generaRPTResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="inviaCarrelloRPT" parameterOrder="inviaCarrelloRPT">
			<input message="tns:ServiziInvioPagamentiTelematici_inviaCarrelloRPT"/>
			<output message="tns:ServiziInvioPagamentiTelematici_inviaCarrelloRPTResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="inviaER" parameterOrder="inviaER">
			<input message="tns:ServiziInvioPagamentiTelematici_inviaER"/>
			<output message="tns:ServiziInvioPagamentiTelematici_inviaERResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="listaConfNEP" parameterOrder="listaConfNEP">
			<input message="tns:ServiziInvioPagamentiTelematici_listaConfNEP"/>
			<output message="tns:ServiziInvioPagamentiTelematici_listaConfNEPResponse"/>
		</operation>
		<operation name="listaDatiRiscossione" parameterOrder="listaDatiRiscossione">
			<input message="tns:ServiziInvioPagamentiTelematici_listaDatiRiscossione"/>
			<output message="tns:ServiziInvioPagamentiTelematici_listaDatiRiscossioneResponse"/>
		</operation>
		<operation name="registraRispostaWisp" parameterOrder="registraRispostaWisp">
			<input message="tns:ServiziInvioPagamentiTelematici_registraRispostaWisp"/>
			<output message="tns:ServiziInvioPagamentiTelematici_registraRispostaWispResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="richiediCopiaRT" parameterOrder="richiediCopiaRT">
			<input message="tns:ServiziInvioPagamentiTelematici_richiediCopiaRT"/>
			<output message="tns:ServiziInvioPagamentiTelematici_richiediCopiaRTResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
		<operation name="verificaRichiesta" parameterOrder="verificaRichiesta">
			<input message="tns:ServiziInvioPagamentiTelematici_verificaRichiesta"/>
			<output message="tns:ServiziInvioPagamentiTelematici_verificaRichiestaResponse"/>
			<fault message="tns:ServiziPagamentiException" name="ServiziPagamentiException"/>
		</operation>
	</portType>
	<binding name="ServiziInvioPagamentiTelematiciBinding" type="tns:ServiziInvioPagamentiTelematici">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="downloadAvviso">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="eliminaRichiesta">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="generaAvviso">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="generaRPT">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="inviaCarrelloRPT">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="inviaER">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="listaConfNEP">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="listaDatiRiscossione">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="registraRispostaWisp">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="richiediCopiaRT">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
		<operation name="verificaRichiesta">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="ServiziPagamentiException">
				<soap:fault name="ServiziPagamentiException" use="literal"/>
			</fault>
		</operation>
	</binding>
	<service name="ServiziInvioPagamentiTelematiciBeanService">
		<port binding="tns:ServiziInvioPagamentiTelematiciBinding" name="ServiziInvioPagamentiTelematiciSOAPPort">
			<soap:address location="http://sdm-pst/servizi/ServiziInvioPagamentiTelematici"/>
		</port>
	</service>
</definitions>