<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><s0:definitions xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://it/mig/sies/type/fogliComplementari" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="trasferisciFoglioComplementare" targetNamespace="http://it/mig/sies/type/fogliComplementari">
	<s0:types>
		<!-- #################### -->
		<!-- #####  TYPES  ###### -->
		<!-- #################### -->
		<xsd:schema>
			<xsd:import namespace="http://it/mig/sies/type/fogliComplementari" schemaLocation="FoglioComplementare.xsd"/>
		</xsd:schema>
		<xs:schema xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://it/mig/sies/type/fogliComplementari" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://it/mig/sies/type/fogliComplementari">
			<xs:element name="trasferisciFoglioComplementare">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="xml" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="trasferisciFoglioComplementareResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
	</s0:types>
	<s0:message name="trasferisciFoglioComplementare">
		<s0:part element="s1:trasferisciFoglioComplementare" name="parameters"/>
	</s0:message>
	<s0:message name="trasferisciFoglioComplementareResponse">
		<s0:part element="s1:trasferisciFoglioComplementareResponse" name="parameters"/>
	</s0:message>
	<s0:portType name="trasferisciFoglioComplementare">
		<s0:operation name="trasferisciFoglioComplementare" parameterOrder="parameters">
			<s0:input message="s1:trasferisciFoglioComplementare"/>
			<s0:output message="s1:trasferisciFoglioComplementareResponse"/>
		</s0:operation>
	</s0:portType>
	<s0:binding name="trasferisciFoglioComplementareSoapBinding" type="s1:trasferisciFoglioComplementare">
		<s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<s0:operation name="trasferisciFoglioComplementare">
			<s2:operation style="document"/>
			<s0:input>
				<s2:body parts="parameters" use="literal"/>
			</s0:input>
			<s0:output>
				<s2:body parts="parameters" use="literal"/>
			</s0:output>
		</s0:operation>
	</s0:binding>
	<s0:service name="trasferisciFoglioComplementare">
		<s0:port binding="s1:trasferisciFoglioComplementareSoapBinding" name="trasferisciFoglioComplementare">
			<s2:address location="https://10.5.207.119:9000/sies/trasferisciFoglioComplementare"/>
		</s0:port>
	</s0:service>
</s0:definitions>