package it.mig.sies.type.foglicomplementari_CUMULO;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * trasferisciFoglioComplementare service = new trasferisciFoglioComplementare();
 * TrasferisciFoglioComplementare portType = service.getTrasferisciFoglioComplementare();
 * portType.trasferisciFoglioComplementare(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "trasferisciFoglioComplementare", targetNamespace = "http://it/mig/sies/type/fogliComplementari", wsdlLocation = "file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/trasferisciFoglioComplementare.wsdl")
public class TrasferisciFoglioComplementare_Service extends Service {

	private final static URL TRASFERISCIFOGLIOCOMPLEMENTARE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementare_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = it.mig.sies.type.foglicomplementari.TrasferisciFoglioComplementare_Service.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/trasferisciFoglioComplementare.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/D:/DATA_RECOVERY/Progetti/WSTestProject/WSTestProject/WebRoot/WEB-INF/wsdl/trasferisciFoglioComplementare.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		TRASFERISCIFOGLIOCOMPLEMENTARE_WSDL_LOCATION = url;
	}

	public TrasferisciFoglioComplementare_Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public TrasferisciFoglioComplementare_Service() {
		super(TRASFERISCIFOGLIOCOMPLEMENTARE_WSDL_LOCATION, new QName(
				"http://it/mig/sies/type/fogliComplementari",
				"trasferisciFoglioComplementare"));
	}

	/**
	 * 
	 * @return returns TrasferisciFoglioComplementare
	 */
	@WebEndpoint(name = "trasferisciFoglioComplementare")
	public TrasferisciFoglioComplementare getTrasferisciFoglioComplementare() {
		return super.getPort(new QName(
				"http://it/mig/sies/type/fogliComplementari",
				"trasferisciFoglioComplementare"),
				TrasferisciFoglioComplementare.class);
	}

}
